### ISSUE TITLE
Titles are undefined

### ISSUE THREAD

**Issue by VladimirMikulic** [PatNeedham/google-it#21]
**Details**
Version: 1.2.0
NPM version: 6.10.3
Node version: 12.8.0

**Bug Info**
As the title says, when I search for something using google-it, sometimes I get links, but without titles in response object.

```javascript
[
  {
    title: undefined,
    link: <some link>
  }
]
```

Why this happens?

**Comment by VladimirMikulic** [comment]
Nevermind, I've fixed it. Requesting merge...

**Comment by fritzwf** [comment]
Any time frame on merging the fix?

**Comment by VladimirMikulic** [comment]
@fritzwf ASAP.

**Comment by PatNeedham** [comment]
@VladimirMikulic thank you for raising this issue and the corresponding PR, which has now been merged. I'll tag a new version `1.2.1` and publish to NPM.

**Comment by VladimirMikulic** [comment]
@PatNeedham no problem, thank you for the great package.
