### ISSUE TITLE
There is a way to do  pagination with this model?

### ISSUE THREAD

**Issue by natigiat** [PatNeedham/google-it#23]
There is a way to do pagination with this model?

**Comment by PatNeedham** [comment]
@natigiat excellent question! At the moment there is no support for pagination. To implement it in a proper way we would need to change the response from every googleIt query to include the number of pages available. However it's currently set up to only return an array of search result entries, not an object. I guess we can allow for an optional flag like `--include-num-pages` which would then change the result to an object, with fields `results` and `numPages` or something like that. And to go along with `--include-num-pages`, we'd also now have the ability to include a `--page` argument for the pagination.

Looks like visiting a specific search results page is as simple as including the `start` query param:

**Comment by Drulac** [comment]
Hello :)
Is there some avancement on this feature :) ?

**Comment by PatNeedham** [comment]
Hi @Drulac , thanks for showing interest in this feature as well. I added the `start` argument as proposed in my previous comment, and the results look like this:

![image](https://user-images.githubusercontent.com/967811/71456275-b250ab00-2766-11ea-9f96-28fb6993075e.png)

This is now available as of `google-it` v1.4.0 on NPM.
