### ISSUE TITLE
Allow providing existing HTML code

### ISSUE THREAD

**Issue by tech234a** [PatNeedham/google-it#38]
In my use case, I would like to be able to reuse the results of an existing request to Google to feed into google-it for parsing. (My tool would be more efficient if it could use the HTML response from Google that has already been received for parsing.) Thanks!

**Comment by PatNeedham** [comment]
This is a great suggestion. Similar functionality exists with the ability to include the path to an HTML file obtained from the network request if it was already made, but allowing to pass that HTML string directly will remove one step from that process!

**Comment by PatNeedham** [comment]
Now available in v1.5.0 via the [`fromString` option](https://github.com/PatNeedham/google-it/pull/43/commits/5389fedcae0ee5164ceb531e7210443d1bd4eca6#diff-eb698ef886ad12edc1d6636aef7041efR126).
