### ISSUE TITLE
JSON is missing actual search results

### ISSUE THREAD

**Issue by hawkeye64** [PatNeedham/google-it#56]
**Version of google-it**
```
google-it@1.5.2 
``` 
**Versions of npm and node**
yarn 1.22.5
node v12.16.0

**Describe the bug**
The returned output has a `,,` in place of the search criteria used, for instance "handling assets". If either of these words are found, or simularities (like `asset`), then double `,,` is seen in place (this is happening because of undefined from the mapping, when there is further children)

**Expected behavior**
To have the actual data

**Screenshots**
I am using `google-it` for a Discord bot to query our docs site for convenience of users
![image](https://user-images.githubusercontent.com/10262924/97611103-59335280-19db-11eb-9a23-5fa9dd029ce2.png)
Notice in the image, there is text `,,` which is where the match for the search criteria would be.

**Additional context**
Diving into the code, I see in the `getSnippet(elem)` method an issue.
```js
function getSnippet(elem) {
  return elem.children.map(function (child) {
    if (!child.data) {
      return child.children.map(function (c) {
        return c.data;
      });
    }

    return child.data;
  }).join('');
}
```
The `return c.data;` is `undefined` where this matching data should be. But, the `c` var has children (`c.children`) that when expanded, `c.children[0].data` does have the matching searched criteria. I suppose Google has done it this way so they can highlight the searched criteria, but google-it is failing to pick it up.
As you can see by this screenshot:
![Screenshot from 2020-10-29 11-43-51](https://user-images.githubusercontent.com/10262924/97611725-28075200-19dc-11eb-9b81-1dcf3bd25aa6.png)

**Comment by hawkeye64** [comment]
I am putting a PR together
![image](https://user-images.githubusercontent.com/10262924/97613691-9baa5e80-19de-11eb-8c9f-37de85d1f865.png)
The data is now available, but it is surrounded by double `,` - need to figure out what's causing that

**Comment by hawkeye64** [comment]
Top image is before fix, second image is after fix
![image](https://user-images.githubusercontent.com/10262924/97615918-83880e80-19e1-11eb-85ab-bae4d4a86149.png)

![image](https://user-images.githubusercontent.com/10262924/97615825-64897c80-19e1-11eb-9a82-3450c0d31190.png)

Still running some tests, but after I get upstream repo set up, expect a PR.

**Comment by PatNeedham** [comment]
@hawkeye64 thank you for spotting this, and providing the PR as well! Really appreciate the example and before/after screenshots. I'll merge this in shortly and publish a new version.

**Comment by PatNeedham** [comment]
Changes added in pull request #57 are now on [google-it@1.5.3](https://www.npmjs.com/package/google-it/v/1.5.3)

**Comment by hawkeye64** [comment]
Thanks for merging it quickly. I can pull it and do a new release myself. :)

**Comment by hawkeye64** [comment]
Something is still not right. The extra commas are appearing. I thought I had resolved this. It occurs when an array is turned to a string in the `join('')` call. I'll see if I can find time to see what happened later today.
![image](https://user-images.githubusercontent.com/10262924/97704000-38203f80-1a77-11eb-98ea-1741762a4f8f.png)
