### ISSUE TITLE
Does not return results anymore

### ISSUE THREAD

**Issue by Mohamed3on** [PatNeedham/google-it#63]
**Version of google-it**
 ```
google-it@1.6.0
```

**Versions of npm and node**
Node: v14.15.3
Yarn: 1.22.4

**Describe the bug**

I have tested this on Mac and windows.

### How to reproduce

```
google-it --query="Obama"
```

**Screenshots**
![image](https://user-images.githubusercontent.com/12295159/104763598-70761680-5766-11eb-8410-86f283993e31.png)

**Comment by flavioro** [comment]
Same mistake.

**Comment by PatNeedham** [comment]
The fix is part of v1.6.1 now available on npm
