### ISSUE TITLE
No results on searching

### ISSUE THREAD

**Issue by Kawba** [PatNeedham/google-it#67]
Hi,

Looks like google-it has stoped working in the last 2 days. Tried on a number of devices and internet connections and no results are being returned but no error messages are being thrown.

Steps to reproduce:
1. sudo npm i -g google-it
2. google-it --query="Facebook"

Thanks,
C

**Comment by Kawba** [comment]
Looks like this is caused by a change in the class used on the div that contains the title and link etc (from 'tF2Cxc' to 'ZINbbc'). This can be fixed by modifying the titleSelector, linkSelector and snippetSelector in utils.js to the below values:

`const titleSelector = 'div.ZINbbc > div:nth-child(1) > a > h3';
const linkSelector = 'div.ZINbbc > div:nth-child(1) > a';
const snippetSelector = 'div.ZINbbc > div:nth-child(2) > div > span';`

Thanks,
C

**Comment by MidSpike** [comment]
Can confirm lack of results on `google-it@1.6.1`

**Comment by ThirdGhostHand** [comment]
I'm sorry. utils.js located where?

**Comment by PatNeedham** [comment]
@Kawba thank you for raising this and suggesting new selectors to use. I can confirm the urls are coming back in a strange format, but the snippet selector doesn't appear to be working (returning undefined):

![image](https://user-images.githubusercontent.com/967811/108942030-341abd80-7624-11eb-9026-d1cb273f64b0.png)

I'm going to try experimenting with different selectors to access the snippet today / tomorrow (hopefully will find the right one within the next hour) & include a `parseGoogleSearchResultUrl` helper function like the one you gave. My gut prediction is that Google will revert back to the original url format, so just in case they do I'll make the function check for how the url is structured. For example:

```
const parseGoogleSearchResultUrl = (url) => {
  if (!url) {
    return undefined;
  }
  if (url.charAt(0) === '/') {
    return querystring.parse(url).url;
  }
  return url;
}
```
The [querystring.parse](https://nodejs.org/docs/latest-v11.x/api/querystring.html#querystring_querystring_parse_str_sep_eq_options) function appears to unescape the `url` query param we want back, so no extra processing necessary past that:
![image](https://user-images.githubusercontent.com/967811/108942909-cff8f900-7625-11eb-8da1-dd7ab4b460d2.png)

Also @ThirdGhostHand the utils.js file is [located here](https://github.com/PatNeedham/google-it/blob/master/src/utils.js)

**Comment by PatNeedham** [comment]
@MidSpike @Kawba can either/both of you please try the just-published on npm v1.6.2 to see if the no results issue still persists?

**Comment by LuanLRT** [comment]
Just tried it and it's working just fine now👏

**Comment by MidSpike** [comment]
@PatNeedham Can confirm working on `1.6.2`
